Release v1.3.2 (#436)
* skip adding to peercache on null

* throttle transactions (#326)

* Read/replication fix (#328)

- All imports are stored in data_info table. This includes brought imports.
- Holding data table refactored.
- JSON importer fixed to behave like other importers.

* wallet check during import

* Update 06_Pink_to_Red_receipt.xml

* Suppress unwanted output (#333)

* Suppress unwanted output

* Properly parse SEND_LOGS

* Use default parameters when creating db

* Send all log levels to stderr

* Update README.md

Updated status. Added reference to our docs on website

* Event emitter refactor (#334)

* dynamic event emitter creation

* minor refactor

* delete vertex internal data (#336)

* Call payout after successful replication (#332)

* Call payout after successful replication

* Add waiting for escrow time

- TimeUtils added for time manipulation

* Fix logging and reading of truffle-test.log and truffle-migrate.log (#337)

* MINOR: properly storing and reading truffle test and migrate logs

* seems we dont need to free up the port anymore

* MINOR: Disable neo4j unit tests and checks

* Fix for Cannot read property 'on' of undefined in EventEmitter.js:584

*  run config && seeders joined

* Fix travis

* npm run install

* npm run install

* Profile parameters (#346)

* add ZKExample to a test suite

* zk example fix

* adjust profile parameters

* fix lint

* bug fix

* Bugfix - Escrow event (#344)

* Add more logs

* fix

* total escrow time fix

* total escrow time fix

* total escrow time fix

* deleted journal

* fix network

* New SC addresses

* add extra logging

* Rolled back smart contracts

* New contracts

* New ABI

* Rolled back contracts and added replication modifier variable and setter to Bidding contract

* Added new contract addresses

* Enables replication modifier in Bidding smart contract

* Sets the contract addresses to ones on develop

* Enables payOut tests for smart contracts

* Fixes profile creation and counting error

* Changes escrow time from seconds to minutes in EscrowInitiated event

* DH replication issue (#345)

* fix DH replication issue, fix TimeUtils

* fix importer

* pack keys for DV

* add simple pack/unpack test

* map _from and _to

* Handling predetermined bids (#339)

* Added predetermined bid flow

* Enabled handling predetermined bids

* Lint fix

* Variable replication factor (#343)

* Add more logs

* fix

* total escrow time fix

* total escrow time fix

* total escrow time fix

* deleted journal

* fix network

* New SC addresses

* add extra logging

* Rolled back smart contracts

* New contracts

* New ABI

* Rolled back contracts and added replication modifier variable and setter to Bidding contract

* Added new contract addresses

* Enables replication modifier in Bidding smart contract

* Sets the contract addresses to ones on develop

* Enables payOut tests for smart contracts

* Fixes profile creation and counting error

* Verification keys fix (#349)

* unpack values

* fix test

* Removed gui (#348)

* import whitelist if more than one, fix (#350)

* low gas warning (#342)

* low gas warning

* Log

* Update bootstrap node on TravisCI (#352)

* MINOR: removing unused folders (#351)

* Flow fixes (#355)

- various fixes discovered during manual tests

* Network refresh (#363)

* refresh network

* skip kademlia log

* Read refactor (#362)

* disable onion

* ToCheap bugfix

* Converts offer to use max token and min stake per byte minute instead of per escrow

* flow fix

* add missing variable

* Abi update

* small fix

* Adds payment events whenever DH acquires tokens

* fix flow

* Fixed createOffer ordering

* get total income and stake

* fix condition

* add stats functions

* enable onion

* fix json

* increase timeout

* fix total escrow time

* fix total escrow time

* multiple fixes

* fix challenges

* vertex sort

* Adds DV_wallet in PurchasePayment event for better houson integration

* Adds basic getters for single data holding stakedAmount and earnings, as well as for single purchase earnings

* fixes

* remove start challenger

* remove refresh

* fixes

* fixes

* enable onion

* log fixes

* log fixes

* add refresh, increase delay, change log level

* adjust prices and set new contracts

* prevent double challenges

* reenable onion

* fix lint

* data location import list fixes

* modify read API

* fix

* send import ID

* small fix

* ignore offer

* small fix

* fix lint

* import id fix

* migrations

* unpack keys

* fix hardcoded values

* enable onion

* Introducing api endpoints log level (#353)

* Error messages in Smart contracts (#358)

* disable onion

* ToCheap bugfix

* Converts offer to use max token and min stake per byte minute instead of per escrow

* flow fix

* add missing variable

* Abi update

* small fix

* Adds payment events whenever DH acquires tokens

* fix flow

* Fixed createOffer ordering

* get total income and stake

* fix condition

* add stats functions

* enable onion

* fix json

* increase timeout

* fix total escrow time

* fix total escrow time

* multiple fixes

* fix challenges

* vertex sort

* Adds DV_wallet in PurchasePayment event for better houson integration

* Adds basic getters for single data holding stakedAmount and earnings, as well as for single purchase earnings

* fixes

* remove start challenger

* remove refresh

* fixes

* fixes

* enable onion

* log fixes

* log fixes

* add refresh, increase delay, change log level

* adjust prices and set new contracts

* prevent double challenges

* reenable onion

* fix lint

* Adds error messages to escrow SC

* Adds error messages to Bidding SC

* Small fixes

* Syncs Bidding SC with BiddingTest SC

* data location import list fixes

* Adds optimizer for smart contract compiling

* Removes giveMeContract functions in rinkeby deployment since deployer.deploy returns contract instance

* Lint fix

* update from houston added (#365)

* synced develop with houston-app DCService,DHService.. (#366)

* synced develop with houston-app DCService,DHService..
* fixed const dcContact
* deleted test console log
* fix tests
* Trying to fix failing gs1-importer-test.js

* Node graphics (#370)

* Async sleep (#371)

* introduce async sleep

* remove timeUtils

* fix sleep

* fix join

* Require msg.sender not zero in smart contracts (#369)

* disable onion

* ToCheap bugfix

* Converts offer to use max token and min stake per byte minute instead of per escrow

* flow fix

* add missing variable

* Abi update

* small fix

* Adds payment events whenever DH acquires tokens

* fix flow

* Fixed createOffer ordering

* get total income and stake

* fix condition

* add stats functions

* enable onion

* fix json

* increase timeout

* fix total escrow time

* fix total escrow time

* multiple fixes

* fix challenges

* vertex sort

* Adds DV_wallet in PurchasePayment event for better houson integration

* Adds basic getters for single data holding stakedAmount and earnings, as well as for single purchase earnings

* fixes

* remove start challenger

* remove refresh

* fixes

* fixes

* enable onion

* log fixes

* log fixes

* add refresh, increase delay, change log level

* adjust prices and set new contracts

* prevent double challenges

* reenable onion

* fix lint

* Adds error messages to escrow SC

* Adds error messages to Bidding SC

* Small fixes

* Syncs Bidding SC with BiddingTest SC

* data location import list fixes

* Adds optimizer for smart contract compiling

* Removes giveMeContract functions in rinkeby deployment since deployer.deploy returns contract instance

* Lint fix

* Add senderNotZero modifier to every function in Bidding, Escrow, and Reading SC

* Sync Bidding.sol with BiddingTest.sol

* Remove senderNotZero in internal functions

* Improvement/api params logs (#367)

* Minor: Logging params with which api endpoints were called

* typo fix

* Small utilities refactor (#357)

* Minor: Moving specific error to be an info log message (#368)

* Bugfix/closeness factor (#375)

- Lowered closeness factor

* Replication modifier in node (#376)

* add replication modifier for offer creation

* change log

* Display required tokens (#380)

* log token amount

* fix lint

* Minor: Better handling in scanario when Arango server is not running (#379)

* Minor: Install specific version of ganache-cli (#378)

* fix multiple bids issue (#382)

* Adding two more unit test for Utilities functions (#381)

- removing async where unnecessary
- disabling after() temporarily to fix irrelevant errors

* Network refresh from peercache (#383)

* enable refresh from peercache

* fix refresh

* refresh starting from closest bucket

* with events (#384)

* skip some Kademlia logs (#385)

* Configurable debug logs level (#372)

* Configurable debug logs level

* improved eth-* logs

* improved logs

* fixing typo

* add more details to logs

* increase timeout (#386)

- increase network timeout

* npm run config

* Network changes (#390)

* change onion settings

* add replay from cache

* fix log

* decrease delay

* error message in nicer form

* return

* change network logs

* return

* remove replay from cache

* refactor logs

* increase listeners, modify logs

* removed increase approval for chosing bids

* removed increase approval for chosing bids and showing balances every 1 min

* low balkance guards

* adapt challenges, add delay for choose

* parse int

* funds for test environment

* Create profile enabled

* wait for challenges (#392)

- wait for verification before starting challenges

* Log update (#391)

* change some logs

* new contracts (#394)

* Docker (#393)

* Update register-node.js

* Update register-node.js

* Update register-node.js

* Update register-node.js

* handle edge errors (#398)

* show ATRAC balance in credits

* Removing .only()

* add api to deposit tokens

* add withdraw to wallet

* fix lint

* emit event for remote control

* Base for protocol testing (#403)

A base framework for testing the protocol from middleware point of view using the in-memory blockchain.

* Introduce package for generating release notes (#399)

* Feed exception and crash logs to PaperTrail (#405)

* Improve createOffer() log (#397)

* MINOR: Improving createOffer log
* improving logs for lst two logged args

* add comments

* fix comment

* Feed exception and crash-like logs to Loggly (#407)

* Latest staging changes (#408)

* fix event category prefixes

* remove explicit logger

* Update .env.example

* Update register-node.js

* Update register-node.js

* Update check-updates.js

* Update supervisord.conf

* Update ot-node.js

* Add package-lock.json file

* Disable caching node_modules on Travis

* Add protocol tests only command [Finishes #158797047]

* Small modification [Delivers #158797047]

* Cathing up with eslint-ing errors in project (#419)

* Introduce timestamps on stdout [Delivers #159411464]

* Add filtering contacts based on IP address and network ID (#418)

Add basic contact filtering based on contact's IP address and contact's network ID.

* hide some logs

* State machine like engine (command sourcing) (#414)

- implement state machine like engine that runs commands backed by database
- implement rich command behavior
-- persistence
-- retry mechanism
-- delay
-- expires
- rewrite DC-DH replication using the engine
- adapt code (fix tests)

* Remove NewRelic  (#422)

* Changelog added
* Removed NewRelic as we are not using it anymore

* Feature/read command sourcing (#424)

* move data-location-request to command

* remove unused method

* expand helper functions

* Add commands for network querying

* Add more DV commands

* Properly handle cancelation of offer

* Read flow fixes

* Handle cancelation of the offer properly

* Dump stack trace on Promise rejection and exception (#425)

* Fix unhandled Promise rejection this.restartNode is not a function (#426)

* Improving config for github release notes package (#423)

- Also incrementing version to be next one comparing to public

* incremented node version to 1.3.1 and deployed new contracts

* Updates fingerprint SC address in rinkeby migration (#430)

* added new bootstrap node address (#432)

* Support bug tracking with bugsnag (#433)

* Add bugsnag

* Remove sensitive data

* disable nat (#431)

* Ignore only development environment when reporting (#435)

* Ignore only development environment when reporting

* Small fix

* Skip infura dependent tests

* New contract and network ID

* Set env and bootstrap